version: "3.8"

services:
  mongo:
    image: mongo:8.0.11
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - dev-network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret123
    networks:
      - dev-network
    ports:
      - "8081:8081"

networks:
  dev-network:
    driver: bridge

volumes:
  mongo_data:
